# Generated by Django 5.2.16 on 2026-07-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('orgs', '0001_initial'),
        ('people', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='hired_from_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='employment',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='people.person'),
        ),
        migrations.AddField(
            model_name='employment',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organisation'),
        ),
        migrations.AddField(
            model_name='employment',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='people.person'),
        ),
        migrations.AddField(
            model_name='rolehistory',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orgs.department'),
        ),
        migrations.AddField(
            model_name='rolehistory',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_history', to='people.person'),
        ),
    ]
