# Generated by Django 5.2.16 on 2026-08-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationnote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='scorecard',
            options={'ordering': ['-created_at']},
        ),
    ]
