# Generated by Django 5.2.16 on 2026-08-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_announcement_policydocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ['-created_at']},
        ),
    ]
