# Generated by Django 5.2.16 on 2026-08-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacknote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='performancereview',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reviewcycle',
            options={'ordering': ['-created_at']},
        ),
    ]
