# Generated by Django 5.2.16 on 2026-08-29 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='transfer_failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payslip',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payslip',
            name='transfer_status',
            field=models.CharField(choices=[('not_initiated', 'Not Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='not_initiated', max_length=16),
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_code', models.CharField(max_length=16)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=32)),
                ('account_name', models.CharField(blank=True, max_length=150)),
                ('recipient_code', models.CharField(blank=True, max_length=64)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to='people.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
