# Generated by Django 5.2.16 on 2026-08-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payslip_paid_at_payslip_transfer_failure_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payoutaccount',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payslip',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='salarystructure',
            options={'ordering': ['-created_at']},
        ),
    ]
