# Generated by Django 5.2.16 on 2026-07-28 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('interview', 'Interview'), ('meeting', 'Meeting')], max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('channel_name', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=12)),
                ('recording_enabled', models.BooleanField(default=True)),
                ('recording_consent_ack', models.BooleanField(default=False)),
                ('recording_sid', models.CharField(blank=True, max_length=128)),
                ('recording_resource_id', models.CharField(blank=True, max_length=256)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterviewParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('host', 'Host'), ('interviewer', 'Interviewer'), ('candidate', 'Candidate'), ('attendee', 'Attendee')], max_length=12)),
                ('agora_uid', models.PositiveIntegerField()),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
    ]
