# Generated by Django 5.2.16 on 2026-07-28 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0001_initial'),
        ('orgs', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.application'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organisation'),
        ),
        migrations.AddField(
            model_name='interviewparticipant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='interviews.interviewsession'),
        ),
        migrations.AddConstraint(
            model_name='interviewparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'person'), name='uniq_participant'),
        ),
        migrations.AddConstraint(
            model_name='interviewparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'agora_uid'), name='uniq_uid_in_channel'),
        ),
    ]
