# Generated by Django 5.2.16 on 2026-08-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewsession',
            options={'ordering': ['-created_at']},
        ),
    ]
