# Generated by Django 5.2.16 on 2026-08-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offboardingtasktemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='personoffboarding',
            options={'ordering': ['-created_at']},
        ),
    ]
