# Generated by Django 5.2.16 on 2026-08-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiscreeningresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='aiusagelog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='attritionflag',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='interviewartifact',
            options={'ordering': ['-created_at']},
        ),
    ]
