# Generated by Django 5.2.16 on 2026-08-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_clock_in_lat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geofencezone',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['-created_at']},
        ),
    ]
